project:
  type: website
  output-dir: docs
  render:
    - nbs/Marquette-SL12-misclassification.ipynb
    - nbs/DSAIL_model.ipynb
    - about.md

website:
  title: "Misdiagnosis of athlete ECG recordings"
  navbar:
    left:
      - href: about.md
        text: About
      - href: nbs/Marquette-SL12-misclassification.ipynb
        text: 1. Case study of athlete misdiagnosis
      - href: nbs/DSAIL_model.ipynb
        text: 2. Benchmarking an open source ECG classifier
        # 3. Domain adaptation methods

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true

execute:
  freeze: true  # Never re-render during project render (PyTorch models...)
# Make sure to save Jupyter notebooks with all code cells run.
# This will make it easier to share results, which can also be published on a 
# documentation website using quarto and Github Pages.
#
# For more info on Publishing to Github Pages, go to:
# https://quarto.org/docs/publishing/github-pages.html
